### ISSUE TITLE
This module crop the files?

### ISSUE THREAD

**Issue by danielchicote** [scriptex/svgo-viewbox#27]
Can this module remove the white space around the document?
Svg-autocrop can do this, but it saves small white space arond.

**Comment by scriptex** [comment]
@danielchicote No, this module only adds the `viewBox` attribute based on `width` and `height` attributes found on the `<svg>`. 

It also adds unique IDs where needed (useful when you create SVG sprites and have a lot of masks for example).

Do you think that cropping functionality should be part of the features provided by this module?

**Comment by scriptex** [comment]
@danielchicote is there anything you'd like to discuss here? If not, please feel free to close the issue.
