### ISSUE TITLE
[Feat]Deal with single file

### ISSUE THREAD

**Issue by RayJason** [scriptex/svgo-viewbox#52]
Sometimes, I just need to deal with a file instead of a folder.

**Comment by RayJason** [comment]
I have upgraded to 2.2.0, but still report an error:
```bash
Error: ENOTDIR: not a directory, scandir './icon.svg'
```

**Comment by scriptex** [comment]
@RayJason can you please show me how you use the module?

**Comment by RayJason** [comment]
> Okay, I need to investigate this. Unfortunately, I can do this as early as Tuesday. 

Have a good weekend

**Comment by scriptex** [comment]
hey, @RayJason, I've published `2.2.1` and tested it - it works for me. Can you please check if it does the job for you as well?

**Comment by RayJason** [comment]
> hey, @RayJason, I've published `2.2.1` and tested it - it works for me. Can you please check if it does the job for you as well?

It's working!🎉
