### ISSUE TITLE
Integrated into the lint-staged workflow

### ISSUE THREAD

**Issue by RayJason** [scriptex/svgo-viewbox#54]
I'm going to integrate svgo-viewbox into the lint-staged workflow. But if I enter it this way, it only works for one file. I'm not sure what's wrong.
```
"lint-staged": {
  "*.{vue,js,jsx,ts,tsx}": [
    "prettier --write",
    "eslint --fix"
  ],
  "*.{css,scss,md,json}": "prettier --write",
  "*.{png,jpg,jpeg}": "tiny-files --key ***",
  "*.svg": "svgo-viewbox -i"
}
```

Can we consider a **default input and output** like svgo?   https://github.com/svg/svgo/issues/691
```
svgo <input> <output>
```
We can also use it quickly without typing '-i'. Thanks for your contribution!

**Comment by scriptex** [comment]
Thanks for the interesting issue, @RayJason. I am not able to find the defaults for SVGO which makes it hard for me to understand what exactly you want to be done 😄 Maybe provide an example?

**Comment by RayJason** [comment]
> Thanks for the interesting issue, @RayJason. I am not able to find the defaults for SVGO which makes it hard for me to understand what exactly you want to be done 😄 Maybe provide an example?

We are using it like this:
```
svgo-viewbox -i ./icon.svg
svgo-viewbox -i ./icon.svg -f ./output
```

I wish it also could be like this:
```
svgo-viewbox ./icon.svg
svgo-viewbox ./icon.svg ./output
```
